import Head from 'next/head'
import Image from 'next/image'
import Layout from '../components/Layout'
import styles from '../styles/Home.module.css'

function HomeCard({ title, icon }) {
  return (
    <div className="bg-slate-700 min-w-1/4 rounded-md p-7 mb-20 text-white text-center">
      <Image src={icon} alt='service_benefits' width="100" height="100" />
      <h2 className="text-xl font-medium mt-10 mb-8 border-b-2 border-slate-300">{title}</h2>
    </div>
  )
}

export default function Home() {
  return (
    <Layout home>
      <Head>
        <title>ESG Metrics</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className='container mx-auto flex justify-around'>
        <HomeCard title='Environmental Care' icon='/environ.png' />
        <HomeCard title='Social Responsible' icon='/social.png' />
        <HomeCard title='Governance Factors' icon='/gover.png' />
      </main>
    </Layout>
  )
}
